name: CI

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5.0.0
      - uses: leafo/gh-actions-lua@v12.0.0
      - uses: actions/cache@v4.3.0
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - run: cargo install selene stylua
      - run: selene lua generate.lua palette.lua
      - run: stylua --check .
      - run: |
          lua generate.lua
          if ! git diff --exit-code; then
            echo "Generated files are out of date!"
            echo "Run \"lua generate.lua\" locally and commit the changes."
            git diff
            exit 1
          fi
